// Mock data for Context Studio — mirrors the backend data model
// Hierarchy: Taxonomy → ConceptScheme → Class → Individual
// Plus: PropertyDefinition (auto-created by relationships) and Relationship triples
window.CS_DATA = (() => {
  const uid = (p) => p + "_" + Math.random().toString(36).slice(2, 8);

  // ---------- Level 1: Taxonomies ----------
  const taxonomies = [
    {
      id: "tax_life",
      node_type: "taxonomy",
      title: "Life Sciences",
      description: "Biological and biomedical knowledge organisation",
      domain: "life",
      version: 4,
    },
    {
      id: "tax_climate",
      node_type: "taxonomy",
      title: "Climate & Environment",
      description: "Earth systems, emissions, and sustainability concepts",
      domain: "climate",
      version: 2,
    },
    {
      id: "tax_sw",
      node_type: "taxonomy",
      title: "Software Engineering",
      description: "Patterns, architectures, and practices",
      domain: "software",
      version: 1,
    },
  ];

  // ---------- Level 2: ConceptSchemes ----------
  // Required parent: taxonomy_id
  const concept_schemes = [
    {
      id: "sch_cell_bio",
      node_type: "concept_scheme",
      title: "Cellular Biology",
      description: "Cells, organelles, and tissue-level concepts",
      taxonomy_id: "tax_life",
      domain: "life",
      version: 3,
    },
    {
      id: "sch_genomics",
      node_type: "concept_scheme",
      title: "Genomics & Proteomics",
      description: "Genes, variants, and gene products",
      taxonomy_id: "tax_life",
      domain: "life",
      version: 5,
    },
    {
      id: "sch_pathways",
      node_type: "concept_scheme",
      title: "Molecular Pathways",
      description: "Reaction networks and signalling cascades",
      taxonomy_id: "tax_life",
      domain: "life",
      version: 1,
    },
    {
      id: "sch_emissions",
      node_type: "concept_scheme",
      title: "Emissions",
      description: "Greenhouse gases and forcing agents",
      taxonomy_id: "tax_climate",
      domain: "climate",
      version: 2,
    },
    {
      id: "sch_impacts",
      node_type: "concept_scheme",
      title: "Climate Impacts",
      description: "Observed and projected effects",
      taxonomy_id: "tax_climate",
      domain: "climate",
      version: 2,
    },
    {
      id: "sch_solutions",
      node_type: "concept_scheme",
      title: "Mitigation & Solutions",
      description: "Renewables and carbon-removal strategies",
      taxonomy_id: "tax_climate",
      domain: "climate",
      version: 1,
    },
    {
      id: "sch_arch",
      node_type: "concept_scheme",
      title: "Architecture Patterns",
      description: "Macro-architectural styles",
      taxonomy_id: "tax_sw",
      domain: "software",
      version: 1,
    },
    {
      id: "sch_testing",
      node_type: "concept_scheme",
      title: "Testing & QA",
      description: "Approaches to verifying behaviour",
      taxonomy_id: "tax_sw",
      domain: "software",
      version: 0,
    },
  ];

  // ---------- Level 3: Classes ----------
  // Required: concept_scheme_id, taxonomy_id. Optional: parent_class_id (intra-scheme tree)
  // Rich attrs: external_references, lexical_senses, data_properties, structural_property_id
  const classes = [
    // Cell bio
    {
      id: "cls_cell",
      title: "Cell",
      description: "Basic structural and functional unit of life",
      concept_scheme_id: "sch_cell_bio",
      taxonomy_id: "tax_life",
      domain: "life",
      parent_class_id: null,
      structural_property_id: "prop_hasPart",
      external_references: [
        { source: "Wikidata", identifier: "Q7868", url: "https://www.wikidata.org/wiki/Q7868" },
        {
          source: "DBpedia",
          identifier: "Cell_(biology)",
          url: "https://dbpedia.org/page/Cell_(biology)",
        },
      ],
      lexical_senses: [
        { label: "cell", language: "en", sense_type: "preferred" },
        { label: "cellule", language: "fr", sense_type: "translation" },
      ],
      data_properties: [
        { key: "avg_diameter_um", value: "10", datatype: "xsd:decimal" },
        { key: "discovered_by", value: "Robert Hooke, 1665", datatype: "xsd:string" },
      ],
      version: 12,
    },
    {
      id: "cls_nucleus",
      title: "Nucleus",
      description: "Membrane-bound organelle containing genetic material",
      concept_scheme_id: "sch_cell_bio",
      taxonomy_id: "tax_life",
      domain: "life",
      parent_class_id: "cls_cell",
      structural_property_id: "prop_hasPart",
      external_references: [{ source: "Wikidata", identifier: "Q40260" }],
      lexical_senses: [{ label: "nucleus", language: "en", sense_type: "preferred" }],
      data_properties: [],
      version: 3,
    },
    {
      id: "cls_mito",
      title: "Mitochondrion",
      description: "Energy-producing organelle",
      concept_scheme_id: "sch_cell_bio",
      taxonomy_id: "tax_life",
      domain: "life",
      parent_class_id: "cls_cell",
      structural_property_id: "prop_hasPart",
      external_references: [{ source: "Wikidata", identifier: "Q39572" }],
      lexical_senses: [
        { label: "mitochondrion", language: "en", sense_type: "preferred" },
        { label: "powerhouse", language: "en", sense_type: "colloquial" },
      ],
      data_properties: [{ key: "origin", value: "endosymbiotic", datatype: "xsd:string" }],
      version: 4,
    },
    {
      id: "cls_membrane",
      title: "Cell Membrane",
      description: "Phospholipid bilayer boundary",
      concept_scheme_id: "sch_cell_bio",
      taxonomy_id: "tax_life",
      domain: "life",
      parent_class_id: "cls_cell",
      structural_property_id: null,
      external_references: [],
      lexical_senses: [],
      data_properties: [],
      version: 1,
    },
    {
      id: "cls_stem",
      title: "Stem Cell",
      description: "Undifferentiated progenitor cell",
      concept_scheme_id: "sch_cell_bio",
      taxonomy_id: "tax_life",
      domain: "life",
      parent_class_id: "cls_cell",
      structural_property_id: null,
      external_references: [{ source: "ConceptNet", identifier: "/c/en/stem_cell" }],
      lexical_senses: [{ label: "stem cell", language: "en", sense_type: "preferred" }],
      data_properties: [],
      version: 6,
    },
    {
      id: "cls_neuron",
      title: "Neuron",
      description: "Electrically excitable cell",
      concept_scheme_id: "sch_cell_bio",
      taxonomy_id: "tax_life",
      domain: "life",
      parent_class_id: "cls_cell",
      structural_property_id: null,
      external_references: [],
      lexical_senses: [{ label: "neuron", language: "en", sense_type: "preferred" }],
      data_properties: [
        { key: "avg_count_human_brain", value: "86000000000", datatype: "xsd:integer" },
      ],
      version: 5,
    },

    // Genomics
    {
      id: "cls_gene",
      title: "Gene",
      description: "DNA sequence encoding a product",
      concept_scheme_id: "sch_genomics",
      taxonomy_id: "tax_life",
      domain: "life",
      parent_class_id: null,
      structural_property_id: "prop_encodes",
      external_references: [{ source: "Wikidata", identifier: "Q7187" }],
      lexical_senses: [{ label: "gene", language: "en", sense_type: "preferred" }],
      data_properties: [{ key: "avg_human_count", value: "~20000", datatype: "xsd:string" }],
      version: 9,
    },
    {
      id: "cls_variant",
      title: "Variant",
      description: "Genetic variation in a population",
      concept_scheme_id: "sch_genomics",
      taxonomy_id: "tax_life",
      domain: "life",
      parent_class_id: "cls_gene",
      structural_property_id: null,
      external_references: [],
      lexical_senses: [{ label: "variant", language: "en", sense_type: "preferred" }],
      data_properties: [],
      version: 2,
    },
    {
      id: "cls_protein",
      title: "Protein",
      description: "Functional gene product",
      concept_scheme_id: "sch_genomics",
      taxonomy_id: "tax_life",
      domain: "life",
      parent_class_id: null,
      structural_property_id: null,
      external_references: [{ source: "Wikidata", identifier: "Q8054" }],
      lexical_senses: [{ label: "protein", language: "en", sense_type: "preferred" }],
      data_properties: [],
      version: 7,
    },

    // Pathways
    {
      id: "cls_pathway",
      title: "Pathway",
      description: "Sequence of molecular interactions",
      concept_scheme_id: "sch_pathways",
      taxonomy_id: "tax_life",
      domain: "life",
      parent_class_id: null,
      structural_property_id: "prop_partOf",
      external_references: [{ source: "Reactome", identifier: "R-HSA" }],
      lexical_senses: [{ label: "pathway", language: "en", sense_type: "preferred" }],
      data_properties: [],
      version: 3,
    },

    // Climate emissions
    {
      id: "cls_co2",
      title: "CO₂",
      description: "Carbon dioxide",
      concept_scheme_id: "sch_emissions",
      taxonomy_id: "tax_climate",
      domain: "climate",
      parent_class_id: null,
      structural_property_id: null,
      external_references: [{ source: "Wikidata", identifier: "Q1997" }],
      lexical_senses: [
        { label: "carbon dioxide", language: "en", sense_type: "preferred" },
        { label: "CO₂", language: "en", sense_type: "symbol" },
      ],
      data_properties: [{ key: "gwp_100yr", value: "1", datatype: "xsd:decimal" }],
      version: 4,
    },
    {
      id: "cls_methane",
      title: "Methane",
      description: "Potent short-lived greenhouse gas",
      concept_scheme_id: "sch_emissions",
      taxonomy_id: "tax_climate",
      domain: "climate",
      parent_class_id: null,
      structural_property_id: null,
      external_references: [{ source: "Wikidata", identifier: "Q37129" }],
      lexical_senses: [{ label: "methane", language: "en", sense_type: "preferred" }],
      data_properties: [{ key: "gwp_100yr", value: "28", datatype: "xsd:decimal" }],
      version: 2,
    },

    // Climate impacts
    {
      id: "cls_warming",
      title: "Global Warming",
      description: "Long-term temperature increase",
      concept_scheme_id: "sch_impacts",
      taxonomy_id: "tax_climate",
      domain: "climate",
      parent_class_id: null,
      structural_property_id: null,
      external_references: [],
      lexical_senses: [{ label: "global warming", language: "en", sense_type: "preferred" }],
      data_properties: [],
      version: 4,
    },
    {
      id: "cls_sealevel",
      title: "Sea Level Rise",
      description: "Ocean expansion and ice melt",
      concept_scheme_id: "sch_impacts",
      taxonomy_id: "tax_climate",
      domain: "climate",
      parent_class_id: "cls_warming",
      structural_property_id: null,
      external_references: [],
      lexical_senses: [{ label: "sea level rise", language: "en", sense_type: "preferred" }],
      data_properties: [],
      version: 1,
    },
    {
      id: "cls_deforest",
      title: "Deforestation",
      description: "Forest cover reduction",
      concept_scheme_id: "sch_impacts",
      taxonomy_id: "tax_climate",
      domain: "climate",
      parent_class_id: null,
      structural_property_id: null,
      external_references: [],
      lexical_senses: [{ label: "deforestation", language: "en", sense_type: "preferred" }],
      data_properties: [],
      version: 2,
    },

    // Solutions
    {
      id: "cls_renew",
      title: "Renewable Energy",
      description: "Solar, wind, and hydro sources",
      concept_scheme_id: "sch_solutions",
      taxonomy_id: "tax_climate",
      domain: "climate",
      parent_class_id: null,
      structural_property_id: null,
      external_references: [{ source: "Wikidata", identifier: "Q12760" }],
      lexical_senses: [{ label: "renewable energy", language: "en", sense_type: "preferred" }],
      data_properties: [{ key: "global_share_2024", value: "0.30", datatype: "xsd:decimal" }],
      version: 5,
    },

    // Arch patterns
    {
      id: "cls_hex",
      title: "Hexagonal Architecture",
      description: "Ports and adapters pattern",
      concept_scheme_id: "sch_arch",
      taxonomy_id: "tax_sw",
      domain: "software",
      parent_class_id: null,
      structural_property_id: null,
      external_references: [{ source: "Wikidata", identifier: "Q5743923" }],
      lexical_senses: [
        { label: "hexagonal architecture", language: "en", sense_type: "preferred" },
        { label: "ports and adapters", language: "en", sense_type: "alias" },
      ],
      data_properties: [{ key: "first_described", value: "2005", datatype: "xsd:gYear" }],
      version: 2,
    },
    {
      id: "cls_ddd",
      title: "Domain-Driven Design",
      description: "Model-centric development approach",
      concept_scheme_id: "sch_arch",
      taxonomy_id: "tax_sw",
      domain: "software",
      parent_class_id: null,
      structural_property_id: null,
      external_references: [],
      lexical_senses: [{ label: "DDD", language: "en", sense_type: "abbreviation" }],
      data_properties: [],
      version: 1,
    },
    {
      id: "cls_micro",
      title: "Microservices",
      description: "Service decomposition pattern",
      concept_scheme_id: "sch_arch",
      taxonomy_id: "tax_sw",
      domain: "software",
      parent_class_id: null,
      structural_property_id: null,
      external_references: [],
      lexical_senses: [{ label: "microservices", language: "en", sense_type: "preferred" }],
      data_properties: [],
      version: 3,
    },
    {
      id: "cls_unit",
      title: "Unit Test",
      description: "Isolated function or class test",
      concept_scheme_id: "sch_testing",
      taxonomy_id: "tax_sw",
      domain: "software",
      parent_class_id: null,
      structural_property_id: null,
      external_references: [],
      lexical_senses: [{ label: "unit test", language: "en", sense_type: "preferred" }],
      data_properties: [],
      version: 0,
    },
  ];

  // ---------- Level 4: Individuals ----------
  // Required: class_ids (ordered list, ≥1). First parent wins on conflicting data props.
  const individuals = [
    {
      id: "ind_brca1",
      node_type: "individual",
      title: "BRCA1",
      description: "BRCA1 DNA repair gene",
      class_ids: ["cls_gene"],
      source: "NCBI",
      confidence: 0.99,
      updated: "2026-04-28",
      version: 2,
    },
    {
      id: "ind_tp53",
      node_type: "individual",
      title: "TP53",
      description: "Tumour-protein p53 gene",
      class_ids: ["cls_gene"],
      source: "NCBI",
      confidence: 0.98,
      updated: "2026-04-26",
      version: 1,
    },
    {
      id: "ind_egfr",
      node_type: "individual",
      title: "EGFR",
      description: "Epidermal growth factor receptor gene",
      class_ids: ["cls_gene"],
      source: "UniProt",
      confidence: 0.97,
      updated: "2026-04-22",
      version: 1,
    },
    {
      id: "ind_p53",
      node_type: "individual",
      title: "p53 protein",
      description: "Tumour suppressor protein",
      class_ids: ["cls_protein"],
      source: "UniProt",
      confidence: 0.99,
      updated: "2026-04-29",
      version: 3,
    },
    {
      id: "ind_apop",
      node_type: "individual",
      title: "Apoptosis pathway",
      description: "Programmed cell death",
      class_ids: ["cls_pathway"],
      source: "Reactome",
      confidence: 0.95,
      updated: "2026-04-12",
      version: 1,
    },
    {
      id: "ind_co2_atm",
      node_type: "individual",
      title: "Atmospheric CO₂ (2025)",
      description: "Annual mean atmospheric CO₂",
      class_ids: ["cls_co2"],
      source: "NOAA",
      confidence: 1.0,
      updated: "2026-04-30",
      version: 2,
    },
    {
      id: "ind_amazon",
      node_type: "individual",
      title: "Amazon deforestation",
      description: "Amazon rainforest forest loss",
      class_ids: ["cls_deforest"],
      source: "WWF",
      confidence: 0.93,
      updated: "2026-04-18",
      version: 4,
    },
    {
      id: "ind_solar_us",
      node_type: "individual",
      title: "US Solar Capacity",
      description: "United States installed solar PV capacity",
      class_ids: ["cls_renew"],
      source: "EIA",
      confidence: 0.96,
      updated: "2026-04-25",
      version: 1,
    },
    {
      id: "ind_hex_alistair",
      node_type: "individual",
      title: "Cockburn\u2019s Hexagonal",
      description: "Original 2005 essay",
      class_ids: ["cls_hex"],
      source: "Manual",
      confidence: 1.0,
      updated: "2026-03-14",
      version: 1,
    },
    {
      id: "ind_evans_ddd",
      node_type: "individual",
      title: "Evans, 2003",
      description: "The original DDD blue book",
      class_ids: ["cls_ddd"],
      source: "Manual",
      confidence: 1.0,
      updated: "2026-03-14",
      version: 1,
    },
  ];

  // ---------- PropertyDefinitions ----------
  // identifier: machine-readable (immutable). title: human (editable).
  // is_relevant: tri-state — null (not evaluated), true (relevant), false (irrelevant).
  const property_definitions = [
    {
      id: "prop_hasPart",
      identifier: "has_part",
      title: "Has Part",
      description: "Mereological containment",
      is_relevant: true,
      origin: "manual",
      version: 3,
    },
    {
      id: "prop_partOf",
      identifier: "part_of",
      title: "Is Part Of",
      description: "Inverse of has_part",
      is_relevant: true,
      origin: "manual",
      version: 2,
    },
    {
      id: "prop_encodes",
      identifier: "encodes",
      title: "Encodes",
      description: "Gene encodes a protein",
      is_relevant: true,
      origin: "manual",
      version: 4,
    },
    {
      id: "prop_emits",
      identifier: "emits",
      title: "Emits",
      description: "Source emits substance",
      is_relevant: true,
      origin: "pipeline:pubmed",
      version: 1,
    },
    {
      id: "prop_relatedTo",
      identifier: "related_to",
      title: "Related To",
      description: "Generic association",
      is_relevant: null,
      origin: "auto",
      version: 0,
    },
    {
      id: "prop_mentionedIn",
      identifier: "mentioned_in",
      title: "Mentioned In",
      description: "Surface co-mention",
      is_relevant: false,
      origin: "pipeline:arxiv",
      version: 0,
    },
    {
      id: "prop_causes",
      identifier: "causes",
      title: "Causes",
      description: "Causal connection",
      is_relevant: true,
      origin: "manual",
      version: 1,
    },
    {
      id: "prop_locatedIn",
      identifier: "located_in",
      title: "Located In",
      description: "Spatial containment",
      is_relevant: null,
      origin: "auto",
      version: 0,
    },
  ];

  // ---------- Relationships ----------
  // (s, t, property_definition_id) triple — unique. No self-loops.
  const relationships = [
    {
      id: "rel_a921",
      source_id: "cls_cell",
      target_id: "cls_nucleus",
      property_definition_id: "prop_hasPart",
      source: "manual",
      confidence: 1.0,
      created: "2026-03-04",
    },
    {
      id: "rel_a922",
      source_id: "cls_cell",
      target_id: "cls_mito",
      property_definition_id: "prop_hasPart",
      source: "manual",
      confidence: 1.0,
      created: "2026-03-04",
    },
    {
      id: "rel_a923",
      source_id: "cls_cell",
      target_id: "cls_membrane",
      property_definition_id: "prop_hasPart",
      source: "manual",
      confidence: 1.0,
      created: "2026-03-04",
    },
    {
      id: "rel_b302",
      source_id: "cls_gene",
      target_id: "cls_protein",
      property_definition_id: "prop_encodes",
      source: "manual",
      confidence: 1.0,
      created: "2026-03-08",
    },
    {
      id: "rel_e811",
      source_id: "ind_brca1",
      target_id: "ind_p53",
      property_definition_id: "prop_relatedTo",
      source: "pubmed pipeline",
      confidence: 0.92,
      created: "2026-04-26",
    },
    {
      id: "rel_c104",
      source_id: "cls_protein",
      target_id: "cls_pathway",
      property_definition_id: "prop_partOf",
      source: "reactome",
      confidence: 0.96,
      created: "2026-04-12",
    },
    {
      id: "rel_d557",
      source_id: "cls_deforest",
      target_id: "cls_co2",
      property_definition_id: "prop_emits",
      source: "manual",
      confidence: 1.0,
      created: "2026-03-14",
    },
    {
      id: "rel_f209",
      source_id: "ind_amazon",
      target_id: "ind_co2_atm",
      property_definition_id: "prop_emits",
      source: "wwf",
      confidence: 0.85,
      created: "2026-04-18",
    },
    {
      id: "rel_g441",
      source_id: "cls_warming",
      target_id: "cls_sealevel",
      property_definition_id: "prop_causes",
      source: "manual",
      confidence: 1.0,
      created: "2026-03-22",
    },
  ];

  const pipelines = [
    {
      id: "pl_extract_pubmed",
      name: "PubMed → Genes & Proteins",
      description: "Extract gene and protein mentions from PubMed abstracts",
      status: "success",
      lastRun: "12m ago",
      avgRunMs: 184000,
      target: "Schema + Data",
      flow: [
        { kind: "source", name: "PubMed", sub: "pubmed_e_utils" },
        { kind: "extract", name: "NER", sub: "gpt-4o-mini" },
        { kind: "resolve", name: "Resolve", sub: "NCBI Gene" },
        { kind: "write", name: "Knowledge Graph", sub: "Genes / Proteins" },
      ],
      recent: { ingested: 412, created: 38, updated: 17, errors: 0 },
    },
    {
      id: "pl_climate_reports",
      name: "IPCC AR6 → Climate Concepts",
      description: "Build taxonomy structure from IPCC chapter headings",
      status: "running",
      lastRun: "now",
      avgRunMs: 312000,
      target: "Schema",
      flow: [
        { kind: "source", name: "IPCC AR6", sub: "PDF corpus" },
        { kind: "extract", name: "Topic mining", sub: "BERTopic" },
        { kind: "resolve", name: "Concept align", sub: "GLOSSARY" },
        { kind: "write", name: "Knowledge Graph", sub: "Climate taxonomy" },
      ],
      recent: { ingested: 28, created: 6, updated: 2, errors: 0 },
    },
    {
      id: "pl_arxiv_se",
      name: "arXiv cs.SE → Patterns",
      description: "Surface software architecture patterns from recent arXiv",
      status: "idle",
      lastRun: "2h ago",
      avgRunMs: 96000,
      target: "Schema + Data",
      flow: [
        { kind: "source", name: "arXiv cs.SE", sub: "OAI-PMH" },
        { kind: "extract", name: "Concept extract", sub: "claude-haiku" },
        { kind: "resolve", name: "Dedup", sub: "embeddings" },
        { kind: "write", name: "Knowledge Graph", sub: "SW patterns" },
      ],
      recent: { ingested: 156, created: 4, updated: 11, errors: 1 },
    },
    {
      id: "pl_eia_solar",
      name: "EIA → Renewable Energy data",
      description: "Pull renewable capacity figures into Climate individuals",
      status: "failed",
      lastRun: "3h ago",
      avgRunMs: 48000,
      target: "Data",
      flow: [
        { kind: "source", name: "EIA API", sub: "eia.gov/v2" },
        { kind: "extract", name: "Schema map", sub: "jq + LLM" },
        { kind: "resolve", name: "Match class", sub: "cls_renew" },
        { kind: "write", name: "Individuals", sub: "cls_renew" },
      ],
      recent: { ingested: 0, created: 0, updated: 0, errors: 1 },
    },
  ];

  const activity = [
    {
      kind: "create",
      who: "pipeline · pubmed",
      what: "Created class",
      subject: "Variant",
      meta: "cls_variant · sch_genomics",
      when: "2m ago",
    },
    {
      kind: "create",
      who: "pipeline · pubmed",
      what: "Created property_definition",
      subject: "encodes",
      meta: "prop_encodes",
      when: "2m ago",
    },
    {
      kind: "update",
      who: "maya@studio",
      what: "Updated relationship",
      subject: "BRCA1 → related_to → p53",
      meta: "rel_e811",
      when: "8m ago",
    },
    {
      kind: "run",
      who: "scheduler",
      what: "Started pipeline",
      subject: "IPCC AR6 → Climate Concepts",
      meta: "pl_climate_reports",
      when: "12m ago",
    },
    {
      kind: "create",
      who: "maya@studio",
      what: "Created relationship",
      subject: "Cell hasPart Nucleus",
      meta: "rel_a921",
      when: "34m ago",
    },
    {
      kind: "delete",
      who: "maya@studio",
      what: "Removed individual",
      subject: "CO₂ (test)",
      meta: "ind_co2_test",
      when: "1h ago",
    },
  ];

  return {
    taxonomies,
    concept_schemes,
    classes,
    individuals,
    property_definitions,
    relationships,
    pipelines,
    activity,
    uid,
  };
})();
